server.port: 8182

spring:
  application.name: ioi-external-integration

  profiles.active: local

  cloud.secrets.directory: spring.cloud.secrets.directory

  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

    hibernate.ddl-auto: validate

    properties:
      hibernate:
        default_schema: person
        jdbc:time_zone: UTC
        show_sql: false

logging.level:
  org.hibernate: WARN
  org.hibernate.type: WARN
  org.springframework: INFO
  com.dais: DEBUG
  com.dais.ioi.scheduler.config.client: WARN
  com.dais.ioi.scheduler.job.listeners: TRACE


feign:
  hystrix.enabled: false
  client.config.default.logger-level: basic

dais:

  cors.allow-origin: "*"

  jwt.endpointMatchersToIgnore: /swagger-ui.html

