name: CI
on:
  workflow_call:
  workflow_dispatch:
jobs:
  java-gradle-build:
    uses: dais-technology/workflow-templates/.github/workflows/java_gradle.yml@main
    with:
      aws-role-to-assum: ${{ secrets.DEFAULT_AWS_ROLE_TO_ASSUME }}
    secrets:
      github-token: ${{ secrets.DAIS_MACHINE_GITHUB_TOKEN }}
      gradle-properties: ${{ secrets.GRADLE_PROPERTIES }}
      dais-machine-github-username: ${{ secrets.DAIS_MACHINE_GITHUB_USERNAME }}
      dais-machine-github-email: ${{ secrets.DAIS_MACHINE_GITHUB_EMAIL }}
