name: CI
on:
  workflow_call:
  workflow_dispatch:
jobs:
  java-gradle-build:
    uses: dais-technology/workflow-templates/.github/workflows/java-gradle.yml@main
    with:
      aws-role-to-assume: arn:aws:iam::991853876083:role/spiderman-eks-master-NodeInstanceRole-1CGN6EINNA20W
    secrets: inherit
